version: '3.8'
services:
  mysql:
    image: mysql:8.3.0
    restart: always
    env_file: log_pass.env
    volumes:
      - ./data/mysql:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  wordpress:
    image: wordpress:6.4.3
    restart: always
    ports:
      - 4000:80
    env_file: log_pass.env
    depends_on:
      - mysql
    volumes:
      - ./data/wp:/var/www/html
    environment:
      - WP_HOME=https://localhost
      - WP_SITEURL=https://localhost
      - WORDPRESS_CONFIG_EXTRA=
          define('WP_HOME', getenv_docker('WP_HOME', 'http://localhost'));
          define('WP_SITEURL', getenv_docker('WP_SITEURL', 'http://localhost'));

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2.1
    restart: always
    ports:
      - 4001:80
    env_file: log_pass.env
    depends_on:
      - mysql
    environment:
      - PMA_HOST=mysql
      - PMA_ABSOLUTE_URI=https://localhost/phpmyadmin/
      - PHPMYADMIN_FORCE_HTTPS=true

  nginx:
    image: nginx:1.24.0
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl_certificate.crt:/etc/ssl/certs/ssl_certificate.crt
      - ./ssl_private_key.key:/etc/ssl/certs/ssl_private_key.key
    ports:
      - 80:80
      - 443:443
    environment:
      - NGINX_PORT=80
 